import express from "express";

const router = express.Router();

const privacyPolicyHtml = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>プライバシーポリシー | KOKKAI DOC</title><style>:root{--primary-color:#1a237e;--text-color:#333;--bg-color:#fff;--border-color:#e0e0e0;}html,body{height:100%;margin:0;padding:0;background:var(--bg-color);color:var(--text-color);font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Hiragino Kaku Gothic ProN\",Meiryo,sans-serif;line-height:1.6;}body{display:flex;justify-content:center;} .policy-container{max-width:960px;width:100%;padding:2rem;box-sizing:border-box;overflow-y:auto;max-height:100vh;-webkit-overflow-scrolling:touch;}h1{font-size:1.8rem;color:var(--primary-color);margin-bottom:1rem;}h2{font-size:1.2rem;color:var(--primary-color);margin-top:1.5rem;}p,li{margin:0.5rem 0;}strong{font-weight:600;}a{color:var(--primary-color);text-decoration:none;}hr{border:none;border-top:1px solid var(--border-color);margin:2rem 0;}</style></head><body><div class="policy-container"><h1>プライバシーポリシー</h1><section><h2>第1条（事業主）</h2><p>本サービスは、個人事業主 <strong>加藤 賢</strong>（以下「事業主」）が運営します。連絡先は <a href="mailto:kokkai.doc@gmail.com">kokkai.doc@gmail.com</a> です。</p></section><section><h2>第2条（定義）</h2><p>「個人情報」とは、個人情報の保護に関する法律（以下「APPI」）第2条第1項に定める情報をいいます。</p></section><section><h2>第3条（取得する情報と方法）</h2><ol><li><strong>募金（Stripe決済）時</strong>：<br>任意の氏名・メールアドレス、必須の決済金額・決済日時。カード番号等は Stripe が PCI-DSS 準拠で管理し、事業主側には保存されません。</li><li><strong>サイト閲覧時</strong>：IPアドレス、ブラウザ情報、アクセス日時等のサーバログ。<br><em>Cookie は使用しません（トラッキング・広告・解析ツールを未導入）。</em></li></ol></section><section><h2>第4条（利用目的）</h2><ul><li>本サービスの提供・運営・品質向上</li><li>募金決済の処理、領収書発行、問い合わせ対応</li><li>不正利用防止・セキュリティ確保・法令遵守</li></ul></section><section><h2>第5条（第三者提供）</h2><p>以下の場合を除き、個人情報を第三者に提供しません。</p><ol><li>ご本人の同意がある場合</li><li>Stripe社など業務委託先に委託目的の範囲で提供する場合</li><li>法令に基づき開示が必要な場合</li></ol></section><section><h2>第6条（国外移転）</h2><p>Stripe社など海外所在事業者へ情報が移転される際は、APPI第28条等に基づき適切な保護措置を講じます。</p></section><section><h2>第7条（安全管理措置）</h2><ul><li>TLS による通信暗号化</li><li>アクセス権限管理・二要素認証</li><li>定期的なログ監査・脆弱性診断</li></ul></section><section><h2>第8条（開示・訂正・利用停止等の請求）</h2><p>本人確認のうえ合理的な期間・方法で対応します。窓口：<a href="mailto:kokkai.doc@gmail.com">kokkai.doc@gmail.com</a></p></section><section><h2>第9条（変更）</h2><p>本ポリシーを改定する際は本サイトで告知し、重要な変更は（任意でメールアドレスを提供している場合に限り）電子メールでも通知します。</p></section><hr><p><small>付則　2025年6月6日施行／最終改定</small></p></div></body></html>
`

const termsAndConditionsHtml = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>利用規約 | KOKKAI DOC</title><style>:root{--primary-color:#1a237e;--text-color:#333;--bg-color:#fff;--border-color:#e0e0e0;}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Kaku Gothic ProN",Meiryo,sans-serif;background:var(--bg-color);color:var(--text-color);line-height:1.6;margin:0;padding:0;}header{background:var(--primary-color);color:#fff;padding:1rem 2rem;}main{max-width:800px;margin:2rem auto;padding:0 1rem;}h1{text-align:center;margin:0;}section{border-bottom:1px solid var(--border-color);padding:1.5rem 0;}section:last-of-type{border-bottom:none;}h2{font-size:1rem;margin:0 0 .5rem;color:var(--primary-color);}ul,ol{margin:.5rem 0 .5rem 1.2rem;padding:0;}li{margin:.3rem 0;}footer{text-align:center;font-size:.9rem;color:var(--text-color);padding:2rem 0;}</style></head><body><header><h1>利用規約</h1></header><main><section><h2>第1条（適用）</h2><p>本規約は、利用者（以下「ユーザ」）が本サービスを利用する一切の行為に適用されます。</p></section><section><h2>第2条（運営主体）</h2><p>本サービスは個人事業主 加藤 賢（以下「事業主」）が運営します。</p></section><section><h2>第3条（利用形態）</h2><ul><li>ユーザ登録は不要です。</li><li>募金時のみ Stripe 決済画面で <strong>任意</strong> で氏名・メールアドレスを入力できます。</li></ul></section><section><h2>第4条（禁止事項）</h2><ul><li>法令または公序良俗に反する行為</li><li>本サービスのネットワーク・システムへの不正アクセス</li><li>本サービスのデータの無断転載・再販</li><li>選挙運動や政治資金規正法等に抵触する恐れのある寄付の勧誘</li></ul></section><section><h2>第5条（知的財産権）</h2><p>本サービス上のコンテンツの著作権等は事業主または正当な権利者に帰属します。API等による再配信には事前の書面許諾が必要です。</p></section><section><h2>第6条（募金／寄付）</h2><ul><li>ユーザは任意の金額を募金として支払えます。</li><li>原則返金不可。ただし二重決済等のシステム不具合が判明した場合は返金します。</li><li>募金は対価性を欠き、ユーザは本サービスに対する持分や議決権を取得しません。</li></ul></section><section><h2>第7条（免責事項）</h2><ul><li>国会議事録等の情報の正確性・完全性を保証しません。</li><li>本サービス利用に起因してユーザに生じた損害について、事業主に故意または重過失がある場合を除き責任を負いません。</li></ul></section><section><h2>第8条（サービスの変更・中断・終了）</h2><p>事業主は事前通知なくサービスの全部または一部を変更・中断・終了することがあります。</p></section><section><h2>第9条（準拠法・裁判管轄）</h2><p>本規約は日本法を準拠法とし、紛争が生じた場合は東京地方裁判所を第一審の専属的合意管轄裁判所とします。</p></section><footer><p>付則　2025年6月6日施行／最終改定</p></footer></main></body></html>`;

router.get("/", (req, res)=>{
res.json({
	"privacy_policy": privacyPolicyHtml,
	"terms_and_conditions": termsAndConditionsHtml,
})});

export default router;
