from openai import OpenAI
import tiktoken
from dotenv import load_dotenv
import os
import time

OPENAI_TOKEN_LIMIT = 128000
load_dotenv()

class Prompter:

	def __init__(self, gpt_model='gpt-4o-mini'):
		"""
		Initializes a Prompter object.

		Args:
			gpt_model (str, optional): The name of the GPT model to use. Defaults to 'gpt-4o'.
		"""
		self.openai_client = OpenAI()
		self.enc = tiktoken.encoding_for_model(gpt_model)
		self.model = gpt_model

	def prompt(self, prompt, system_prompt=None, shorten_ok=True, retry=2):
		"""
		Sends a prompt to the OpenAI API and returns the generated reply.

		Args:
			prompt (str): The user input message to be sent for completion.
			system_prompt (str, optional): A system-level prompt that provides context or instructions for the model. Defaults to None.
			shorten_ok (bool, optional): Whether the prompt can be shortened if it exceeds the token limit. Defaults to True.
			retry (int, optional): Number of times to retry the request in case of failure. Defaults to 2.

		Returns:
			str: The content of the reply generated by the OpenAI model.

		Raises:
			Exception: If the prompt is too long and `shorten_ok` is False, or if no reply is received after the specified number of retries.
		"""

		count = 0
		messages = []
		if system_prompt is not None:
			messages.append({"role": "system", "content": system_prompt})
		
		tokens = self.enc.encode(prompt)
		if len(tokens) > OPENAI_TOKEN_LIMIT and not shorten_ok:
			raise Exception('Prompt too long for OpenAI API, either turn on shorten_ok or shoten the prompt')
		reply = None
		while len(self.enc.encode(prompt)) > OPENAI_TOKEN_LIMIT:
			print('Shotening prompt')
			prompt = prompt[:int(len(prompt)*0.9)]
			
		while count < retry:
			try:
				completion = self.openai_client.chat.completions.create(
					model=self.model,
					messages=messages+[{"role": "user", "content": prompt}])

				reply = completion.choices[0].message.content
				time.sleep(2)
				break
			except Exception as e:
				print(e)
				count += 1
				continue
		if reply is None:
			raise Exception('Failed to get reply for prompt of length', len(prompt), 'after', count, 'retries')	
	
		return reply
		