# from openai import OpenAI,AsyncOpenAI
# import tiktoken
from dotenv import load_dotenv
import logging
import os
import random
import time
import os
# from agents import Agent, Runner, WebSearchTool, RunConfig, set_default_openai_client, HostedMCPTool
from google import genai
from google.genai import errors as genai_errors
from google.genai import types
# import anthropic

logger = logging.getLogger(__name__)

# HTTP status codes that mean "retry later" rather than "your request is broken":
# 429 = RESOURCE_EXHAUSTED (rate limit / quota), 503 = UNAVAILABLE (model overloaded),
# 500 = INTERNAL, 504 = DEADLINE_EXCEEDED. These are handled with exponential backoff.
RETRYABLE_STATUS_CODES = {429, 500, 503, 504}

# OPENAI_TOKEN_LIMIT = 128000
load_dotenv()

# class GPTPrompter:

#     def __init__(self, gpt_model='gpt-o3-mini'):
#         """
#         Initializes a Prompter object.

#         Args:
#             gpt_model (str, optional): The name of the GPT model to use. Defaults to 'gpt-4o'.
#         """
#         self.openai_client = OpenAI()
#         try:
#             self.enc = tiktoken.encoding_for_model(gpt_model)
#         except Exception as e:
#             print(e)
#             self.enc = tiktoken.encoding_for_model('gpt-4o-mini')
#         self.model = gpt_model

#     def prompt(self, prompt, system_prompt=None, shorten_ok=True, retry=2):
#         """
#         Sends a prompt to the OpenAI API and returns the generated reply.

#         Args:
#             prompt (str): The user input message to be sent for completion.
#             system_prompt (str, optional): A system-level prompt that provides context or instructions for the model. Defaults to None.
#             shorten_ok (bool, optional): Whether the prompt can be shortened if it exceeds the token limit. Defaults to True.
#             retry (int, optional): Number of times to retry the request in case of failure. Defaults to 2.

#         Returns:
#             str: The content of the reply generated by the OpenAI model.

#         Raises:
#             Exception: If the prompt is too long and `shorten_ok` is False, or if no reply is received after the specified number of retries.
#         """

#         count = 0
#         messages = []
#         if system_prompt is not None:
#             messages.append({"role": "system", "content": system_prompt})
		
#         tokens = self.enc.encode(prompt)
#         if len(tokens) > OPENAI_TOKEN_LIMIT and not shorten_ok:
#             raise Exception('Prompt too long for OpenAI API, either turn on shorten_ok or shoten the prompt')
#         reply = None
#         while len(self.enc.encode(prompt)) > OPENAI_TOKEN_LIMIT:
#             print('Shotening prompt')
#             prompt = prompt[:int(len(prompt)*0.9)]
			
#         while count < retry:
#             try:
#                 completion = self.openai_client.chat.completions.create(
#                     model=self.model,
#                     messages=messages+[{"role": "user", "content": prompt}])

#                 reply = completion.choices[0].message.content
#                 print("reply", reply)
#                 time.sleep(2)
#                 break
#             except Exception as e:
#                 print(e)
#                 count += 1
#                 continue
#         if reply is None:
#             raise Exception('Failed to get reply for prompt of length', len(prompt), 'after', count, 'retries')	
	
#         return reply
	
# class DeepResearchGPT:
# 	def __init__(self, gpt_model="o3-deep-research"):
# 		self.gpt_model = gpt_model
# 		self.openai_client = OpenAI()
# 		try:
# 			self.enc = tiktoken.encoding_for_model(gpt_model)
# 		except Exception as e:
# 			print(e)
# 			self.enc = tiktoken.encoding_for_model('gpt-4o-mini')
	
# 	def prompt(self, prompt, system_prompt=None, shorten_ok=True, retry=2):
# 		"""
# 		Sends a prompt to the OpenAI API and returns the generated reply.
# 		"""
# 		print("PROMPTING {}".format(self.gpt_model))
# 		print(system_prompt+"\n\n\n"+prompt)
# 		response = self.openai_client.responses.create(
# 			model=self.gpt_model,
# 			input=[
# 				{
# 					"role":"developer",
# 					"content": [
# 						{
# 							"type": "input_text",
# 							"text": system_prompt
# 						}
# 					]
# 				},
# 				{
# 					"role": "user",
# 					"content": [
# 						{
# 							"type": "input_text",
# 							"text": prompt
# 						}
# 					]
# 				}
# 			],
# 			# reasoning={
# 			# 	"summary":"auto"
# 			# },	
# 			tools=[
# 				{
# 					"type": "web_search_preview"
# 				}
# 			]
# 		)
# 		citations = []
# 		for i, citation in enumerate(response.output[-1].content[0].annotations):
# 			citation_idx = i+1
# 			title = citation.title
# 			url = citation.url
# 			start_idx = citation.start_index
# 			end_idx = citation.end_index
# 			citation_dict = {
# 				"citation_idx": citation_idx,
# 				"title": title,
# 				"url": url,
# 				"start_idx": start_idx,
# 				"end_idx": end_idx
# 			}
# 			citations.append(citation_dict)
# 		return response.output[-1].content[0].text, citations
	
# 	async def async_prompt(self, prompt, system_prompt=None, shorten_ok=True, retry=2):
# 		research_agent = Agent(
# 			name="Research Agent",
# 			model="o4-mini-deep-research-2025-06-26",
# 			tools=[WebSearchTool()],
# 			instructions=system_prompt
# 		)
# 		result_stream = Runner.run_streamed(
# 			research_agent,
# 			prompt
# 		)

# 		async for ev in result_stream.stream_events():
# 			if ev.type == "agent_updated_stream_event":
# 				print(f"\n--- switched to agent: {ev.new_agent.name} ---")
# 				print(f"\n--- RESEARCHING ---")
# 			elif ev.type == "raw_response_event" and hasattr(ev.data, "item") and hasattr(ev.data.item, "action"):
# 				action = ev.data.item.action or {}
# 				if action.get("type") == "search":
# 					print(f"[Web search] query={action.get('query')!r}")

		# return result_stream.final_output
	
class DeepResearchGemini:
	def __init__(self, model_name="gemini-3.5-flash"):
		self.client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
		self.model_name = model_name
	
	@staticmethod
	def _is_retryable(exc: Exception) -> bool:
		"""True when the API is busy/overloaded and the call is worth retrying."""
		if isinstance(exc, genai_errors.ServerError):
			# 5xx from the model backend (500/503/504) are all transient.
			return True
		if isinstance(exc, genai_errors.ClientError):
			# Only 429 (RESOURCE_EXHAUSTED) is retryable among 4xx; others are our fault.
			return getattr(exc, "code", None) in RETRYABLE_STATUS_CODES
		return False

	def prompt(
		self,
		prompt,
		system_prompt="",
		shorten_ok=True,
		retry=5,
		base_delay=2.0,
		max_delay=60.0,
	):
		"""Send a prompt to Gemini, retrying with exponential backoff + jitter when
		the API is busy (429 RESOURCE_EXHAUSTED / 503 UNAVAILABLE / other 5xx).

		Args:
			retry: max number of attempts (not just extra tries).
			base_delay: initial backoff in seconds; doubles each attempt.
			max_delay: cap on the backoff sleep in seconds.
		"""
		print("---------------------------------------------------------------")

		# Make the request
		print("PROMPTING GEMINI")

		print(system_prompt+"\n\n\n"+prompt)

		last_exc: Exception | None = None
		for attempt in range(retry):
			try:
				response = self.client.models.generate_content(
					model=self.model_name,
					contents=system_prompt+"\n\n\n"+prompt,
					config={"tools": [{"google_search": {}}]},
				)
				break
			except Exception as exc:
				if not self._is_retryable(exc) or attempt == retry - 1:
					raise
				last_exc = exc
				# Exponential backoff with full jitter: sleep ~ U(0, min(cap, base * 2**attempt)).
				delay = min(max_delay, base_delay * (2 ** attempt))
				delay = random.uniform(0, delay)
				logger.warning(
					"Gemini busy (%s); attempt %d/%d, backing off %.1fs",
					getattr(exc, "code", type(exc).__name__),
					attempt + 1,
					retry,
					delay,
				)
				time.sleep(delay)
		else:  # pragma: no cover - loop always breaks or raises
			raise RuntimeError("Gemini request failed after retries") from last_exc

		print("RESPONSE", response)
		response_text = response.text
		# supports = response.candidates[0].grounding_metadata.grounding_supports
		# chunks = response.candidates[0].grounding_metadata.grounding_chunks

		print("RESPONSE TEXT", response_text)
		print("---------------------------------------------------------------")
		return response_text
